### ISSUE TITLE
Better train & predict panel

### ISSUE THREAD

**Issue by florianfendt** [mlr-org/mlr_shiny#27]
Currently we have separate sub menus for train, predict and performance.
All look really empty. Maybe summarize in one tab?
Also we need to review the predict tab specifically:
Do we really need to display the data that is uploaded for prediction?
Also it should be possible to extract the predictions afterwards
(corresponding issue #18 )

**Comment by PhilippPro** [comment]
- Summarizing is maybe ok. 

- > Do we really need to display the data that is uploaded for prediction?
 
 I think this is good if you want to reassure yourself, that you want to predict the right data (and why possibly prediction does not work)

**Comment by Coorsaa** [comment]
The train and benchmark panels seem to be broken right now. The area where I should be able to choose a learner within the train panel is empty for me (the dropdwown menu is missing). Hence, I'm not able to train or predict.

**Comment by Coorsaa** [comment]
I'm not quite sure if we should keep both buttons on the learner panel. Especially the "choose learner" button was created due to the fact that changing the learner list resulted in resetting the learner hyperpars. However, since clicking on that button, which is necessary when adding or removing a learner, resets the learner hyperpars anyway, we could go a step back and do that again automatically unless we don't have a solution to keep the hyperpar settings of a single learner. 
Moreover maybe the "construct learners" button should be placed in a bit more obvious position on the panel. At first I just didn't recognize it.

**Comment by PhilippPro** [comment]
I really like the new learner section! Maybe put the hyperparameter overview at the buttom and the sethyperpars and probability estimation at the top. The construct learner buttom is far below everything else and hard to find, for me it was too, when I tested it. 

Would also be cool to directly change the hyperpars in the table or via buttons somehow, instead of list() (I think new users do not have any idea of how setting them here, without any explanation or experience with mlr) but this is probably not so easy.

**Comment by florianfendt** [comment]
Yes the UI is far from perfect, I admit.
I just pushed this so we can build on it now.
I dislike that when adding a learner the current set hyper pars are removed as well.
Having that "choose learner button" was just the easy solution for now.
I also want to have buttons and sliders for the hyper pars.
These are the 2 things I will work on next.

**Comment by PhilippPro** [comment]
Looks really good now. Probability measures are not settable when measuring performance at the moment... (in the benchmark section it works)

**Comment by florianfendt** [comment]
Closing. Panel should be ok for now. Reopen if we can suggest improvements/ find bugs

**Comment by florianfendt** [comment]
Closing. Panel should be ok for now. Reopen if we can suggest improvements/ find bugs
