### ISSUE TITLE
After setting probability to "yes", setting threshold to slow ends up in a loop

### ISSUE THREAD

**Issue by PhilippPro** [mlr-org/mlr_shiny#54]
First thing I have to say is, that I really like all the new features, especially the new section with preprocessing. 

I discovered a small bug. After setting your classification task you can go to your learner section and set your learner to probability "yes". If you immediately click on the next learner (you have to be quick enough) the shiny app keeps changing from the first to the second learner all the time. Hope you can reproduce this small bug.

**Comment by Coorsaa** [comment]
Yes, it's reproducible, I faced the same bug.

**Comment by Coorsaa** [comment]
I changed the title, since we have the new learner tab. However the bug is similar why I didn't open another issue.
When I set probability = "yes", the threshold inputs apear. I type in one of them e.g. "0.5" too slowly, I end up in a loop. It seems that the value of the numericInput field refreshes too fast. In fact, do we need it to refresh?

**Comment by florianfendt** [comment]
Mhm, unfortunate I'll look into it. Should probably just be a missing isolate
