### ISSUE TITLE
Error when predicting randomForest with se estimation

### ISSUE THREAD

**Issue by Coorsaa** [mlr-org/mlr_shiny#64]
When training the randomForest on bh.task with se estimation, I get an error when predicting: **Error:** argument must be coercible to non-negative integer. This continues of course for performance, visualizations and benchmarking as well, since prediction is not possible.

**Comment by Coorsaa** [comment]
Maybe its related to another bug I get. While I only need to select one variable for prediction plots when doing regression, I get the same error message when trying to do that using the randomForest. However, selecting two variables ends up in the correct prediction plot

**Comment by florianfendt** [comment]
Yes I'm aware of this error. Most probably we are facing problems with other learners too since we explicitly set the default values of the params.
In this case we get the error because of a requirement of another parameter where the default shouldn't be set. This is not easily avoidable at the moment and I don't think we should write an ugly workaround atm because from my understanding ParamHelpers should soonish support better handling of dependent parameter settings and we can then find a nicer way of handling this.

What we need though is an reactive value that handles such situations and writes an informative error message

**Comment by florianfendt** [comment]
Closing here. We are fetching and printing such as errors. Every core-mlr error should be fixed there.
